import csv
from bs4 import BeautifulSoup
from urllib.request import urlopen

# List of HTML files
html_files = [
    "file:///C:/Users/Ernandes/Downloads/1/1.html",
    "file:///C:/Users/Ernandes/Downloads/1/2.html",
    "file:///C:/Users/Ernandes/Downloads/1/3.html",
    "file:///C:/Users/Ernandes/Downloads/1/4.html",
    "file:///C:/Users/Ernandes/Downloads/1/5.html",
    "file:///C:/Users/Ernandes/Downloads/1/6.html",
    "file:///C:/Users/Ernandes/Downloads/1/7.html",
    "file:///C:/Users/Ernandes/Downloads/1/8.html",
    "file:///C:/Users/Ernandes/Downloads/1/9.html",
    "file:///C:/Users/Ernandes/Downloads/1/10.html",
    "file:///C:/Users/Ernandes/Downloads/1/11.html",
    "file:///C:/Users/Ernandes/Downloads/1/12.html",
    "file:///C:/Users/Ernandes/Downloads/1/13.html",
    "file:///C:/Users/Ernandes/Downloads/1/14.html",
    "file:///C:/Users/Ernandes/Downloads/1/15.html",
    "file:///C:/Users/Ernandes/Downloads/1/16.html",
    "file:///C:/Users/Ernandes/Downloads/1/17.html",
    "file:///C:/Users/Ernandes/Downloads/1/18.html",
    "file:///C:/Users/Ernandes/Downloads/1/19.html",
    "file:///C:/Users/Ernandes/Downloads/1/20.html",
    "file:///C:/Users/Ernandes/Downloads/1/21.html",
    "file:///C:/Users/Ernandes/Downloads/1/22.html",
    "file:///C:/Users/Ernandes/Downloads/1/23.html",
    "file:///C:/Users/Ernandes/Downloads/1/24.html",
    "file:///C:/Users/Ernandes/Downloads/1/25.html",
    "file:///C:/Users/Ernandes/Downloads/1/26.html",
    "file:///C:/Users/Ernandes/Downloads/1/27.html",
    "file:///C:/Users/Ernandes/Downloads/1/28.html",
    "file:///C:/Users/Ernandes/Downloads/1/29.html",
    "file:///C:/Users/Ernandes/Downloads/1/30.html",
    "file:///C:/Users/Ernandes/Downloads/1/31.html",
    "file:///C:/Users/Ernandes/Downloads/1/32.html",
    "file:///C:/Users/Ernandes/Downloads/1/33.html",
    "file:///C:/Users/Ernandes/Downloads/1/34.html",
    "file:///C:/Users/Ernandes/Downloads/1/35.html",
    "file:///C:/Users/Ernandes/Downloads/1/36.html",
    "file:///C:/Users/Ernandes/Downloads/1/37.html",
    "file:///C:/Users/Ernandes/Downloads/1/38.html",
    "file:///C:/Users/Ernandes/Downloads/1/39.html",
    "file:///C:/Users/Ernandes/Downloads/1/40.html",
    "file:///C:/Users/Ernandes/Downloads/1/41.html",
    "file:///C:/Users/Ernandes/Downloads/1/42.html",
    "file:///C:/Users/Ernandes/Downloads/1/43.html",
    "file:///C:/Users/Ernandes/Downloads/1/44.html",
    "file:///C:/Users/Ernandes/Downloads/1/45.html",
    "file:///C:/Users/Ernandes/Downloads/1/46.html",
    "file:///C:/Users/Ernandes/Downloads/1/47.html",
    "file:///C:/Users/Ernandes/Downloads/1/48.html",
    "file:///C:/Users/Ernandes/Downloads/1/49.html",
    "file:///C:/Users/Ernandes/Downloads/1/50.html",
    "file:///C:/Users/Ernandes/Downloads/1/51.html",
    "file:///C:/Users/Ernandes/Downloads/1/52.html",
    "file:///C:/Users/Ernandes/Downloads/1/53.html",
    "file:///C:/Users/Ernandes/Downloads/1/54.html",
    "file:///C:/Users/Ernandes/Downloads/1/55.html",
    "file:///C:/Users/Ernandes/Downloads/1/56.html",
    "file:///C:/Users/Ernandes/Downloads/1/57.html",
    
    "file:///C:/Users/Ernandes/Downloads/1/59.html",
    "file:///C:/Users/Ernandes/Downloads/1/60.html",
    "file:///C:/Users/Ernandes/Downloads/1/61.html",
    "file:///C:/Users/Ernandes/Downloads/1/62.html",
    "file:///C:/Users/Ernandes/Downloads/1/63.html",
    "file:///C:/Users/Ernandes/Downloads/1/64.html",
    "file:///C:/Users/Ernandes/Downloads/1/65.html",
    "file:///C:/Users/Ernandes/Downloads/1/66.html",
    "file:///C:/Users/Ernandes/Downloads/1/67.html",
    "file:///C:/Users/Ernandes/Downloads/1/68.html",
    "file:///C:/Users/Ernandes/Downloads/1/69.html",
    "file:///C:/Users/Ernandes/Downloads/1/70.html",
    "file:///C:/Users/Ernandes/Downloads/1/71.html",
    "file:///C:/Users/Ernandes/Downloads/1/72.html",
    "file:///C:/Users/Ernandes/Downloads/1/73.html",
    "file:///C:/Users/Ernandes/Downloads/1/74.html",
    "file:///C:/Users/Ernandes/Downloads/1/75.html",
    "file:///C:/Users/Ernandes/Downloads/1/76.html",
    "file:///C:/Users/Ernandes/Downloads/1/77.html",
    "file:///C:/Users/Ernandes/Downloads/1/78.html",
    "file:///C:/Users/Ernandes/Downloads/1/79.html",
    "file:///C:/Users/Ernandes/Downloads/1/80.html",
    "file:///C:/Users/Ernandes/Downloads/1/81.html",
    "file:///C:/Users/Ernandes/Downloads/1/82.html",
    "file:///C:/Users/Ernandes/Downloads/1/83.html",
    "file:///C:/Users/Ernandes/Downloads/1/84.html",
    "file:///C:/Users/Ernandes/Downloads/1/85.html",
    "file:///C:/Users/Ernandes/Downloads/1/86.html",
    "file:///C:/Users/Ernandes/Downloads/1/87.html",
    "file:///C:/Users/Ernandes/Downloads/1/88.html",
    "file:///C:/Users/Ernandes/Downloads/1/89.html",
    "file:///C:/Users/Ernandes/Downloads/1/90.html",
    "file:///C:/Users/Ernandes/Downloads/1/91.html",
    "file:///C:/Users/Ernandes/Downloads/1/92.html",
    "file:///C:/Users/Ernandes/Downloads/1/93.html",
    "file:///C:/Users/Ernandes/Downloads/1/94.html",
    "file:///C:/Users/Ernandes/Downloads/1/95.html",
    "file:///C:/Users/Ernandes/Downloads/1/96.html",
    "file:///C:/Users/Ernandes/Downloads/1/97.html",
    "file:///C:/Users/Ernandes/Downloads/1/98.html",
    "file:///C:/Users/Ernandes/Downloads/1/99.html",
    "file:///C:/Users/Ernandes/Downloads/1/100.html",
    "file:///C:/Users/Ernandes/Downloads/11/1.html",
    "file:///C:/Users/Ernandes/Downloads/11/2.html",
    "file:///C:/Users/Ernandes/Downloads/11/3.html",
    "file:///C:/Users/Ernandes/Downloads/11/4.html",
    "file:///C:/Users/Ernandes/Downloads/11/5.html",
    "file:///C:/Users/Ernandes/Downloads/11/6.html",
    "file:///C:/Users/Ernandes/Downloads/11/7.html",
    "file:///C:/Users/Ernandes/Downloads/11/8.html",
    "file:///C:/Users/Ernandes/Downloads/11/9.html",
    "file:///C:/Users/Ernandes/Downloads/11/10.html",
    "file:///C:/Users/Ernandes/Downloads/11/11.html",
    "file:///C:/Users/Ernandes/Downloads/11/12.html",
    "file:///C:/Users/Ernandes/Downloads/11/13.html",
    "file:///C:/Users/Ernandes/Downloads/11/14.html",
    "file:///C:/Users/Ernandes/Downloads/11/15.html",
    "file:///C:/Users/Ernandes/Downloads/11/16.html",
    "file:///C:/Users/Ernandes/Downloads/11/17.html",
    "file:///C:/Users/Ernandes/Downloads/11/18.html",
    "file:///C:/Users/Ernandes/Downloads/11/19.html",
    "file:///C:/Users/Ernandes/Downloads/11/20.html",
    "file:///C:/Users/Ernandes/Downloads/11/21.html",
    "file:///C:/Users/Ernandes/Downloads/11/22.html",
    "file:///C:/Users/Ernandes/Downloads/11/23.html",
    "file:///C:/Users/Ernandes/Downloads/11/24.html",
    "file:///C:/Users/Ernandes/Downloads/11/25.html",
    "file:///C:/Users/Ernandes/Downloads/11/26.html",
    "file:///C:/Users/Ernandes/Downloads/11/27.html",
    "file:///C:/Users/Ernandes/Downloads/11/28.html",
    "file:///C:/Users/Ernandes/Downloads/11/29.html",
    "file:///C:/Users/Ernandes/Downloads/11/30.html",
    "file:///C:/Users/Ernandes/Downloads/11/31.html",
    "file:///C:/Users/Ernandes/Downloads/11/32.html",
    "file:///C:/Users/Ernandes/Downloads/11/33.html",
    "file:///C:/Users/Ernandes/Downloads/11/34.html",
    "file:///C:/Users/Ernandes/Downloads/11/35.html",
    "file:///C:/Users/Ernandes/Downloads/11/36.html",
    "file:///C:/Users/Ernandes/Downloads/11/37.html",
    "file:///C:/Users/Ernandes/Downloads/11/38.html",
    "file:///C:/Users/Ernandes/Downloads/11/39.html",
    
]

# CSV file to store website values
csv_file = "websites.csv"

# Iterate over the HTML files
for html_file in html_files:
    page = urlopen(html_file)
    html_bytes = page.read()
    html = html_bytes.decode("utf-8")
    soup = BeautifulSoup(html, features="html.parser")
    websites = soup.find_all('td', class_='row_name')

    # Append the websites to the CSV file
    with open(csv_file, 'a', newline='') as file:
        writer = csv.writer(file)

        for website in websites:
            website_value = website.get_text(strip=True)
            writer.writerow([website_value])
            print(f"Website: {website_value}")

print("Websites appended to:", csv_file)